# Generated by Django 2.2.13 on 2021-07-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=50, null=True)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('book_name', models.CharField(blank=True, max_length=50, null=True)),
                ('book_count', models.IntegerField(blank=True, default='0', null=True)),
                ('book_cover', models.ImageField(default='book_cover.jpg', upload_to='')),
                ('index_page', models.ImageField(default='index_page.jpg', upload_to='')),
                ('give_count', models.IntegerField(blank=True, default='0', null=True)),
                ('given_by', models.CharField(blank=True, max_length=50, null=True)),
                ('order_count', models.IntegerField(blank=True, default='0', null=True)),
                ('order_by', models.CharField(blank=True, max_length=50, null=True)),
                ('order_to', models.CharField(blank=True, max_length=50, null=True)),
                ('student_details', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('alert_level', models.IntegerField(blank=True, default='0', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
